name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: 'https://front.serverest.dev'
      EMAIL: ${{ secrets.EMAIL }}
      SENHA: ${{ secrets.SENHA }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar Cypress em modo headless
        run: npm run test:e2e

      
      - name: Upload de screenshots e vídeos se falhar
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
